=== Skatteetaten/saf-t/SAF-T_Financial_1.3/Grouping Category Code/XML/Grouping_Category_Code.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2017 rel. 3 sp1 (x64) (http://www.altova.com) by ï»¿Skatteetaten (Skatteetaten) -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:vc="http://www.w3.org/2007/XMLSchema-versioning" elementFormDefault="qualified" attributeFormDefault="unqualified" vc:minVersion="1.1">
	<xs:element name="GroupingCategoryCode">
		<xs:annotation>
			<xs:documentation>General Ledger Grouping Categories and Codes for mapping in Norwegian SAF-T Financial.</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Account" maxOccurs="unbounded">
					<xs:annotation>
						<xs:documentation>GL Accounts</xs:documentation>
					</xs:annotation>
					<xs:complexType>
						<xs:sequence>
							<xs:element name="GroupingCategory">
								<xs:annotation>
									<xs:documentation>Type of category. </xs:documentation>
								</xs:annotation>
								<xs:simpleType>
									<xs:restriction base="xs:string">
										<xs:minLength value="2"/>
										<xs:maxLength value="200"/>
									</xs:restriction>
								</xs:simpleType>
							</xs:element>
							<xs:element name="CategoryDescription" maxOccurs="unbounded">
								<xs:annotation>
									<xs:documentation>Descripton of the category.</xs:documentation>
								</xs:annotation>
								<xs:complexType>
									<xs:simpleContent>
										<xs:extension base="xs:string">
											<xs:attribute name="ISOLanguageCode">
												<xs:annotation>
													<xs:documentation>Three-letter language code according to ISO 639-3 standared. Example: NOB for Norwegian.</xs:documentation>
												</xs:annotation>
												<xs:simpleType>
													<xs:restriction base="xs:string">
														<xs:length value="3"/>
													</xs:restriction>
												</xs:simpleType>
											</xs:attribute>
										</xs:extension>
									</xs:simpleContent>
								</xs:complexType>
							</xs:element>
							<xs:element name="GroupingCode">
								<xs:annotation>
									<xs:documentation>Code for the type of category.</xs:documentation>
								</xs:annotation>
							</xs:element>
							<xs:element name="CodeDescription" maxOccurs="unbounded">
								<xs:annotation>
									<xs:documentation>Descripton of the code.</xs:documentation>
								</xs:annotation>
								<xs:complexType>
									<xs:simpleContent>
										<xs:extension base="xs:string">
											<xs:attribute name="ISOLanguageCode">
												<xs:annotation>
													<xs:documentation>Three-letter language code according to ISO 639-3 standared. Example: NOB for Norwegian.</xs:documentation>
												</xs:annotation>
												<xs:simpleType>
													<xs:restriction base="xs:string">
														<xs:length value="3"/>
													</xs:restriction>
												</xs:simpleType>
											</xs:attribute>
										</xs:extension>
									</xs:simpleContent>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== Skatteetaten/saf-t/Grouping Category Code/XML/KA_K_Grouping_Category_Code_2020.xml
<?xml version="1.0" encoding="UTF-8"?>
<GroupingCategoryCode xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="Grouping_Category_Code.xsd">
  <Account>
    <GroupingCategory>KA_K</GroupingCategory>
    <CategoryDescription ISOLanguageCode="NOB">KOSTRA Arts_K</CategoryDescription>
    <GroupingCode>010</GroupingCode>
    <CodeDescription ISOLanguageCode="NOB">Fastlønn</CodeDescription>
  </Account>
  <Account>
    <GroupingCategory>KA_K</GroupingCategory>
    <CategoryDescription ISOLanguageCode="NOB">KOSTRA Arts_K</CategoryDescription>
    <GroupingCode>020</GroupingCode>
    <CodeDescription ISOLanguageCode="NOB">lønn til vikarer</CodeDescription>
  </Account>
  <Account>
    <GroupingCategory>KA_K</GroupingCategory>
    <CategoryDescription ISOLanguageCode="NOB">KOSTRA Arts_K</CategoryDescription>
    <GroupingCode>030</GroupingCode>
    <CodeDescription ISOLanguageCode="NOB">lønn til ekstrahjelp</CodeDescription>
  </Account>
  <Account>
    <GroupingCategory>KA_K</GroupingCategory>
    <CategoryDescription ISOLanguageCode="NOB">KOSTRA Arts_K</CategoryDescription>
    <GroupingCode>040</GroupingCode>
    <CodeDescription ISOLanguageCode="NOB">Overtidslønn</CodeDescription>
  </Account>
  <Account>
    <GroupingCategory>KA_K</GroupingCategory>
    <CategoryDescription ISOLanguageCode="NOB">KOSTRA Arts_K</CategoryDescription>
    <GroupingCode>050</GroupingCode>
    <CodeDescription ISOLanguageCode="NOB">Annen lønn og trekkpliktige godtgjørelser</CodeDescription>
  </Account>
  <Account>
    <GroupingCategory>KA_K</GroupingCategory>
    <CategoryDescription ISOLanguageCode="NOB">KOSTRA Arts_K</CategoryDescription>
    <GroupingCode>070</GroupingCode>
    <CodeDescription ISOLanguageCode="NOB">lønn til vedlikehold, påkostning, nybygg og nyanlegg</CodeDescription>
  </Account>
  <Account>
    <GroupingCategory>KA_K</GroupingCategory>
    <CategoryDescription ISOLanguageCode="NOB">KOSTRA Arts_K</CategoryDescription>
    <GroupingCode>075</GroupingCode>
    <CodeDescription ISOLanguageCode="NOB">lønn til renhold</CodeDescription>
  </Account>
  <Account>
    <GroupingCategory>KA_K</GroupingCategory>
    <CategoryDescription ISOLanguageCode="NOB">KOSTRA Arts_K</CategoryDescription>
    <GroupingCode>080</GroupingCode>
    <CodeDescription ISOLanguageCode="NOB">Godtgjørelser til folkevalgte</CodeDescription>
  </Account>
  <Account>
    <GroupingCategory>KA_K</GroupingCategory>
    <CategoryDescription ISOLanguageCode="NOB">KOSTRA Arts_K</CategoryDescription>
    <GroupingCode>089</GroupingCode>
    <CodeDescription ISOLanguageCode="NOB">Trekkpliktig, opplysningspliktig, ikke arbeidsgiveravgiftspliktig lønn</CodeDescription>
  </Account>
  <Account>
    <GroupingCategory>KA_K</GroupingCategory>
    <CategoryDescription ISOLanguageCode="NOB">KOSTRA Arts_K</CategoryDescription>
    <GroupingCode>090</GroupingCode>
    <CodeDescription ISOLanguageCode="NOB">Pensjonsinnskudd og trekkpliktige forsikringsordninger</CodeDescription>
  </Account>
  <Account>
    <GroupingCategory>KA_K</GroupingCategory>
    <CategoryDescription ISOLanguageCode="NOB">KOSTRA Arts_K</CategoryDescription>
    <GroupingCode>099</GroupingCode>
    <CodeDescription ISOLanguageCode="NOB">Arbeidsgiveravgift</CodeDescription>
  </Account>
  <Account>
    <GroupingCategory>KA_K</GroupingCategory>
    <CategoryDescription ISOLanguageCode="NOB">KOSTRA Arts_K</CategoryDescription>
    <GroupingCode>100</GroupingCode>
    <CodeDescription ISOLanguageCode="NOB">Kontormateriell</CodeDescription>
  </Account>
  <Account>
    <GroupingCategory>KA_K</GroupingCategory>
    <CategoryDescription ISOLanguageCode="NOB">KOSTRA Arts_K</CategoryDescription>
    <GroupingCode>105</GroupingCode>
    <CodeDescription ISOLanguageCode="NOB">Undervisningsmateriell</CodeDescription>
  </Account>
  <Account>
    <GroupingCategory>KA_K</GroupingCategory>
    <CategoryDescription ISOLanguageCode="NOB">KOSTRA Arts_K</CategoryDescription>
    <GroupingCode>110</GroupingCode>
    <CodeDescription ISOLanguageCode="NOB">Medisinsk forbruksmateriell</CodeDescription>
  </Account>
  <Account>
    <GroupingCategory>KA_K</GroupingCategory>
    <CategoryDescription ISOLanguageCode="NOB">KOSTRA Arts_K</CategoryDescription>
    <GroupingCode>114</GroupingCode>
    <CodeDescription ISOLanguageCode="NOB">Medikamenter</CodeDescription>
  </Account>
  <Account>
    <GroupingCategory>KA_K</GroupingCategory>
    <CategoryDescription ISOLanguageCode="NOB">KOSTRA Arts_K</CategoryDescription>
    <GroupingCode>115</GroupingCode>
    <CodeDescription ISOLanguageCode="NOB">Matvarer</CodeDescription>
  </Account>
  <Account>
    <GroupingCategory>KA_K</GroupingCategory>
    <CategoryDescription ISOLanguageCode="NOB">KOSTRA Arts_K</CategoryDescription>
    <GroupingCode>120</GroupingCode>
    <CodeDescription ISOLanguageCode="NOB">Samlepost for annet forbruksmateriell, varer og tjenester</CodeDescription>
  </Account>
  <Account>
    <GroupingCategory>KA_K</GroupingCategory>
    <CategoryDescription ISOLanguageCode="NOB">KOSTRA Arts_K</CategoryDescription>
    <GroupingCode>130</GroupingCode>
    <CodeDescription ISOLanguageCode="NOB">Post, bank, telefon, internett, bredbånd</CodeDescription>
  </Account>
  <Account>
    <GroupingCategory>KA_K</GroupingCategory>
    <CategoryDescription ISOLanguageCode="NOB">KOSTRA Arts_K</CategoryDescription>
    <GroupingCode>140</GroupingCode>
    <CodeDescription ISOLanguageCode="NOB">Annonser, reklame, informasjon</CodeDescription>
  </Account>
  <Account>
    <GroupingCategory>KA_K</GroupingCategory>
    <CategoryDescription ISOLanguageCode="NOB">KOSTRA Arts_K</CategoryDescription>
    <GroupingCode>150</GroupingCode>
    <CodeDescription ISOLanguageCode="NOB">Opplæring og kurs</CodeDescription>
  </Account>
  <Account>
    <GroupingCategory>KA_K</GroupingCategory>
    <CategoryDescription ISOLanguageCode="NOB">KOSTRA Arts_K</CategoryDescription>
    <GroupingCode>160</GroupingCode>
    <CodeDescription ISOLanguageCode="NOB">Utgifter og godtgjørelser for reiser, diett, bil mv. som er opplysningspliktige</CodeDescription>
  </Account>
  <Account>
    <GroupingCategory>KA_K</GroupingCategory>
    <CategoryDescription ISOLanguageCode="NOB">KOSTRA Arts_K</CategoryDescription>
    <GroupingCode>165</GroupingCode>
    <CodeDescription ISOLanguageCode="NOB">Andre opplysningspliktige godtgjørelser</CodeDescription>
  </Account>
  <Account>
    <GroupingCategory>KA_K</GroupingCategory>
    <CategoryDescription ISOLanguageCode="NOB">KOSTRA Arts_K</CategoryDescription>
    <GroupingCode>170</GroupingCode>
    <CodeDescription ISOLanguageCode="NOB">Transport og reise</CodeDescription>
  </Account>
  <Account>
    <GroupingCategory>KA_K</GroupingCategory>
    <CategoryDescription ISOLanguageCode="NOB">KOSTRA Arts_K</CategoryDescription>
    <GroupingCode>180</GroupingCode>
    <CodeDescription ISOLanguageCode="NOB">Strøm</CodeDescription>
  </Account>
  <Account>
    <GroupingCategory>KA_K</GroupingCategory>
    <CategoryDescription ISOLanguageCode="NOB">KOSTRA Arts_K</CategoryDescription>
    <GroupingCode>181</GroupingCode>
    <CodeDescription ISOLanguageCode="NOB">Fjernvarme og fjernkjøling</CodeDescription>
  </Account>
  <Account>
    <GroupingCategory>KA_K</GroupingCategory>
    <CategoryDescription ISOLanguageCode="NOB">KOSTRA Arts_K</CategoryDescription>
    <GroupingCode>182</GroupingCode>
    <CodeDescription ISOLanguageCode="NOB">Fyringsolje og fyringsparafin</CodeDescription>
  </Account>
  <Account>
    <GroupingCategory>KA_K</GroupingCategory>
    <CategoryDescription ISOLanguageCode="NOB">KOSTRA Arts_K</CategoryDescription>
    <GroupingCode>183</GroupingCode>
    <CodeDescription ISOLanguageCode="NOB">Naturgass og andre fossile gasser</CodeDescription>
  </Account>
  <Account>
    <GroupingCategory>KA_K</GroupingCategory>
    <CategoryDescription ISOLanguageCode="NOB">KOSTRA Arts_K</CategoryDescription>
    <GroupingCode>184</GroupingCode>
    <CodeDescription ISOLanguageCode="NOB">Bioenergi</CodeDescription>
  </Account>
  <Account>
    <GroupingCategory>KA_K</GroupingCategory>
    <CategoryDescription ISOLanguageCode="NOB">KOSTRA Arts_K</CategoryDescription>
    <GroupingCode>185</GroupingCode>
    <CodeDescription ISOLanguageCode="NOB">Forsikringer, vakthold og sikring
    </CodeDescription>
  </Account>
  <Account>
    <GroupingCategory>KA_K</GroupingCategory>
    <CategoryDescription ISOLanguageCode="NOB">KOSTRA Arts_K</CategoryDescription>
    <GroupingCode>190</GroupingCode>
    <CodeDescription ISOLanguageCode="NOB">Leie av lokaler og grunn</CodeDescription>
  </Account>
  <Account>
    <GroupingCategory>KA_K</GroupingCategory>
    <CategoryDescription ISOLanguageCode="NOB">KOSTRA Arts_K</CategoryDescription>
    <GroupingCode>195</GroupingCode>
    <CodeDescription ISOLanguageCode="NOB">Avgifter, gebyrer, lisenser o.l.</CodeDescription>
  </Account>
  <Account>
    <GroupingCategory>KA_K</GroupingCategory>
    <CategoryDescription ISOLanguageCode="NOB">KOSTRA Arts_K</CategoryDescription>
    <GroupingCode>200</GroupingCode>
    <CodeDescription ISOLanguageCode="NOB">kjøp og finansiell leasing av driftsmidler</CodeDescription>
  </Account>
  <Account>
    <GroupingCategory>KA_K</GroupingCategory>
    <CategoryDescription ISOLanguageCode="NOB">KOSTRA Arts_K</CategoryDescription>
    <GroupingCode>209</GroupingCode>
    <CodeDescription ISOLanguageCode="NOB">Medisinsk utstyr</CodeDescription>
  </Account>
  <Account>
    <GroupingCategory>KA_K</GroupingCategory>
    <CategoryDescription ISOLanguageCode="NOB">KOSTRA Arts_K</CategoryDescription>
    <GroupingCode>210</GroupingCode>
    <CodeDescription ISOLanguageCode="NOB">kjøp og leie av transportmidler</CodeDescription>
  </Account>
  <Account>
